/* CUSTOMER TABLE */
CREATE TABLE Customer(
	Cus_ID SMALLINT IDENTITY(01, 1) PRIMARY KEY NOT NULL,
	Cus_Name VARCHAR(30),
	Cus_Email VARCHAR(30),
	Cus_Phone_Num VARCHAR(15),
	Cus_Address VARCHAR(30));

/* CATEGORY TABLE */
CREATE TABLE Category(
	Category_ID SMALLINT IDENTITY (0001, 1) PRIMARY KEY NOT NULL,
	Category_Name VARCHAR(30));

/* SELLERS TABLE */
CREATE TABLE Sellers (
    Sell_ID SMALLINT IDENTITY(01, 1) PRIMARY KEY,
    Sell_Name VARCHAR(50),
    Sell_Phone_Num VARCHAR(15),
    Sell_Address VARCHAR(50),
    Followers INT,
    Number_of_Products INT,
);

/* PRODUCT TABLE */
CREATE TABLE Product (
	Pro_ID SMALLINT IDENTITY(01, 1) PRIMARY KEY NOT NULL,
	Pro_Name VARCHAR(50),
	Category_ID SMALLINT FOREIGN KEY REFERENCES Category(Category_ID),
	Sell_ID SMALLINT FOREIGN KEY REFERENCES Sellers(Sell_ID),
	Pro_Price REAL,
	Stock_Quantities SMALLINT,
);

/* ORDERS TABLE */
CREATE TABLE Orders(
	Order_ID SMALLINT IDENTITY (001, 1) PRIMARY KEY not null,
	Cus_ID SMALLINT not null FOREIGN KEY REFERENCES Customer(Cus_ID),
	Pro_ID SMALLINT not null FOREIGN KEY REFERENCES Product(Pro_ID),
   	Order_Date DATE);

/* CART TABLE */
CREATE TABLE Cart (
    Cart_ID SMALLINT IDENTITY(000001, 1) PRIMARY KEY NOT NULL,
    Cus_ID SMALLINT FOREIGN KEY REFERENCES Customer(Cus_ID),
    Order_ID SMALLINT FOREIGN KEY REFERENCES Orders(Order_ID),
    Total_Items SMALLINT,
    Total_Price REAL,
);

/* SHIPMENT TABLE */
CREATE TABLE Shipment(
    Ship_ID VARCHAR(30) PRIMARY KEY NOT NULL,
    Order_ID SMALLINT FOREIGN KEY REFERENCES Orders(Order_ID),
    Delivery_date DATE,
    Ship_Address VARCHAR(50),
    Shipment_Method VARCHAR(10),
    Status VARCHAR(10));

/* PAYMENT TABLE */
CREATE TABLE  Payment(
    Pay_ID SMALLINT IDENTITY(001,1) PRIMARY KEY not null,  
    Order_ID SMALLINT not null FOREIGN KEY REFERENCES Orders(Order_ID),
    Pay_date DATE,
    Pay_Method VARCHAR(20));

/* DISCOUNT TABLE */
CREATE TABLE  Discount(
    Dis_Code VARCHAR(30) PRIMARY KEY not null,
    Pro_ID SMALLINT not null FOREIGN KEY REFERENCES Product(Pro_ID),
    Dis_Rate REAL not null,
    Start_Date DATE,
    Expire_Date DATE);

/* REVIEW TABLE */
CREATE TABLE Review (
    Review_ID SMALLINT IDENTITY (2001, 1)PRIMARY KEY,
    Cust_ID SMALLINT FOREIGN KEY REFERENCES Customer(Cus_ID),
    Pro_ID SMALLINT FOREIGN KEY REFERENCES Product(Pro_ID),
    Rating REAL,
    Date_of_Review DATE
);
